In [20]:
# Import Libraries
import csv
import numpy as np
import tensorflow as tf
import tensorflow_recommenders as tfrs
import os
import pandas as pd

In [21]:
os.getcwd()

'c:\\Users\\kottu\\OneDrive\\Documents\\GitHub\\Songs-recommender\\scripts'

In [22]:
 # set the directories
n_songs_in = 3

base_dir = 'c:\\Users\\kottu\\OneDrive\\Documents\\GitHub\\Songs-recommender\\'
index_model_dir = base_dir + '/model'

In [27]:
# create a list of users and songs
users_songs = {}
with open(base_dir + 'data/processed/users_songs.csv') as file:
    reader = csv.reader(file)
    next(reader)
    for line in reader:
        user = int(line[0])
        song = int(line[1])
        try:
            users_songs[user].append(song)
        except:
            users_songs[user] = [song]
users_songs

{0: [15372,
  93191,
  100477,
  103324,
  74034,
  52937,
  18494,
  75689,
  10985,
  129647,
  121672,
  37655],
 1: [77979, 101076, 115855, 48405, 65062, 28444, 112113],
 2: [59200, 33006, 7762, 81416],
 3: [26184, 59271, 92997, 105022, 28204, 10029, 3073],
 4: [122029, 104280, 54529, 21734, 99068],
 5: [37559, 111352, 34299, 106118, 39123, 34468, 126730, 128909, 115602],
 6: [53878, 121304],
 7: [123616,
  107519,
  32402,
  92457,
  42057,
  80890,
  77594,
  84193,
  17821,
  61104,
  102340,
  89165,
  93757,
  44971,
  82622,
  115693,
  64547,
  5739],
 8: [2569, 52699, 25445, 64514],
 9: [44827, 88536, 70797, 54129],
 10: [104696, 76110, 34409],
 11: [65218, 31580, 19062],
 12: [118592, 28416, 8029, 44860],
 13: [51372, 885, 115778],
 14: [80507,
  109634,
  58679,
  52565,
  108100,
  43044,
  51647,
  20193,
  17317,
  75431,
  118098,
  94195,
  88518,
  69827,
  48894],
 15: [16511,
  50292,
  46730,
  54332,
  105597,
  42372,
  81490,
  106776,
  4938,
  67638,
  11323

In [29]:
user_idxs = {}
with open(base_dir + 'data/processed/user_idxs.csv') as file:
    reader = csv.reader(file)
    next(reader)
    for line in reader:
        user_idxs[line[1]] = line[0]

user_idxs

{'5a905f000fc1ff3df7ca807d57edb608863db05d': '0',
 '1a849df9dabb15845eb932d46d81e2fd77176786': '1',
 '3ff7a31452eeabd7a4e07f0d243c674e3d0adf46': '2',
 '66166f4f57bb897f1f8e2aae6f53f776088f43d8': '3',
 '95942345306393998eb3a051ae5fa3c4d5afbaa4': '4',
 '8814f5d1f1d7177aa2efb6de6454504f3bb7b7bc': '5',
 '06b31818386e598017a475f8e349b3ca31ba3178': '6',
 'e21477efb83bd323205ce6f5bd662f3df9d477e5': '7',
 '4691b4c353503da2c108e372ff056a9ac847c4d1': '8',
 '3fef4e71c70ae99ef8a4da00e431f9cdb2b1b729': '9',
 'be0a4b64e9689c46e94b5a9a9c7910ee61aeb16f': '10',
 '52df18b9b1235ac56507cb4119fc5b3f6f010dcd': '11',
 '4208d4ac45e7caab7167a4ea6d34e759a6b9a1fc': '12',
 'dd88ea94f605a63d9fc37a214127e3f00e85e42d': '13',
 'ec25e3d78ea8374869a772dc58bb903528a3c9cc': '14',
 '95b2ebf54cd69d732fa433ee8994be5818793efb': '15',
 '42c9fba813dd9ca8ca3673277a0f923b6845a7a6': '16',
 '645a5b400d31ce69611137da3ebd35d11d4dda4a': '17',
 '51182330ee3e55d808df31a951032692c5cefe8a': '18',
 'e06fdac28cdd1d69d89de27868d5f02f71c2ee4

In [32]:
song_idxs = {}
with open(base_dir + 'data/processed/song_idxs.csv') as file:
    reader = csv.reader(file)
    next(reader)
    for line in reader:
        song_idxs[line[1]] = line[0]

song_idxs

{'SOZZONR12A58A7F429': '0',
 'SOQEPUD12AC90716D9': '1',
 'SOEBRJU12A58A7BCC5': '2',
 'SOVZCFJ12AF729A86C': '3',
 'SOQPIWR12AF72AD1DF': '4',
 'SOECRBA12AB01816A7': '5',
 'SONXYLQ12A58A7B1F8': '6',
 'SOHMZUP12AB018F79F': '7',
 'SOKNLMG12AF729FB53': '8',
 'SOPQRKO12A8C133B4A': '9',
 'SOCNLBO12A6D4F7517': '10',
 'SOBUGNR12A58A7DCF1': '11',
 'SOANTZY12AB018379D': '12',
 'SOIRKID12AB01839F8': '13',
 'SODNADO12A6D4F89D5': '14',
 'SOGFANW12A6D4F6821': '15',
 'SOCHHOB12A6D4FADE3': '16',
 'SOTYFIK12AB01846FA': '17',
 'SOLEXIL12A8C132DD3': '18',
 'SOKIWXJ12AB0182036': '19',
 'SOOLNMT12A58A7E8B8': '20',
 'SOINNJR12A6D4FA3B4': '21',
 'SOQIOMM12A8C13F3A7': '22',
 'SOQHRJF12A8C1351AC': '23',
 'SONQPZX12AB0184521': '24',
 'SOTODHT12A58A7E7C1': '25',
 'SOTLHLO12AB0183305': '26',
 'SOAAUPC12AAA8C861F': '27',
 'SOCRRDP12A58A7E519': '28',
 'SOTZIZN12AF729E6F6': '29',
 'SOFNUUI12A58A76B27': '30',
 'SOAZQYA12AF72A02E3': '31',
 'SOVJCKN12A8C142D4E': '32',
 'SODFYCS12A8C13656F': '33',
 'SOQFODN12A6D4FBFE8': '

In [33]:
n_users = len(user_idxs)
n_songs = len(song_idxs)
print('n_users', n_users)
print('n_songs', n_songs)
# create a dictionary of inputs and outputs
dataset = {'songs': [], 'user': []}
for user, songs in users_songs.items():
    for _ in range(len(songs) * 5):
        # randomly select n_songsns_in from the user's isbns
        selected_songs = np.random.choice(songs, n_songs_in)
        # add them to the inputs
        dataset['songs'].append(selected_songs)
        # add the user to the output
        dataset['user'].append(user)
dataset

n_users 64774
n_songs 130791


{'songs': [array([ 74034, 121672, 129647]),
  array([37655, 74034, 75689]),
  array([93191, 18494, 74034]),
  array([74034, 15372, 18494]),
  array([100477,  93191,  93191]),
  array([ 10985,  18494, 103324]),
  array([ 93191, 129647,  37655]),
  array([100477,  15372,  93191]),
  array([ 18494, 103324,  10985]),
  array([100477,  93191, 129647]),
  array([ 18494, 121672,  37655]),
  array([ 75689, 103324, 103324]),
  array([ 10985, 100477, 100477]),
  array([74034, 37655, 10985]),
  array([100477,  15372,  74034]),
  array([100477,  10985,  52937]),
  array([52937, 37655, 74034]),
  array([ 37655, 121672,  74034]),
  array([52937, 37655, 18494]),
  array([121672,  75689, 121672]),
  array([ 10985,  74034, 129647]),
  array([18494, 93191, 75689]),
  array([74034, 10985, 74034]),
  array([74034, 52937, 52937]),
  array([ 93191, 103324,  52937]),
  array([ 15372,  74034, 121672]),
  array([129647,  93191,  18494]),
  array([10985, 10985, 10985]),
  array([18494, 74034, 75689]),
  array([

In [34]:
# create a permutation to randomly shuffle all of the above data
# a permutation is created first so the same order can be applied
# to the inputs and the outputs

permutation = np.random.permutation(len(dataset['songs']))
# apply the above permutation to the inputs and the outputs
dataset = {
    'songs': np.asarray(dataset['songs'])[permutation],
    'user': np.asarray(dataset['user'])[permutation]
}
# convert the above dictionary to a TF Dataset
dataset = tf.data.Dataset.from_tensor_slices(dataset)

print('len_dataset', permutation.shape[0])
# print an example of the data in the dataset
for d in dataset.take(1):
    print(d)

len_dataset 1989205
{'songs': <tf.Tensor: shape=(3,), dtype=int32, numpy=array([54060, 54060, 54060])>, 'user': <tf.Tensor: shape=(), dtype=int32, numpy=27678>}


In [35]:
# create the query and candidate models
n_embedding_dimensions = 24

## QUERY
songs_in_in = tf.keras.Input(shape=(n_songs_in))
songs_in_emb = tf.keras.layers.Embedding(n_songs+1, n_embedding_dimensions)(songs_in_in)
songs_in_emb_avg = tf.keras.layers.AveragePooling1D(pool_size=3)(songs_in_emb)
query = tf.keras.layers.Flatten()(songs_in_emb_avg)
query_model = tf.keras.Model(inputs=songs_in_in, outputs=query)

## CANDIDATE
user_in = tf.keras.Input(shape=(1))
user_emb = tf.keras.layers.Embedding(n_users+1, n_embedding_dimensions)(user_in)
candidate = tf.keras.layers.Flatten()(user_emb)
candidate_model = tf.keras.Model(inputs=user_in, outputs=candidate)

In [36]:
# TFRS TASK SETUP
candidates = dataset.batch(128).map(lambda x: candidate_model(x['user']))
metrics = tfrs.metrics.FactorizedTopK(candidates=candidates)
task = tfrs.tasks.Retrieval(metrics=metrics)


## TFRS MODEL CLASS
class Model(tfrs.Model):
    def __init__(self, query_model, candidate_model):
        super().__init__()
        self._query_model = query_model
        self._candidate_model = candidate_model
        self._task = task

    def compute_loss(self, features, training=False):
        query_embedding = self._query_model(features['songs'])
        candidate_embedding = self._candidate_model(features['user'])
        return self._task(query_embedding, candidate_embedding)

## COMPILE AND TRAIN MODEL
model = Model(query_model, candidate_model)
# load model weights - this is to resume training
# model._query_model.load_weights(weights_dir.format('query'))
# model._candidate_model.load_weights(weights_dir.format('candidate'))

model.compile(optimizer=tf.keras.optimizers.Adagrad(learning_rate=0.1))
model.fit(dataset.repeat().shuffle(300_000).batch(4096), steps_per_epoch=50, epochs=30, verbose=1)

Epoch 1/30
 5/50 [==>...........................] - ETA: 3:02:59 - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 4.8828e-05 - factorized_top_k/top_50_categorical_accuracy: 1.9531e-04 - factorized_top_k/top_100_categorical_accuracy: 6.8359e-04 - loss: 34068.4508 - regularization_loss: 0.0000e+00 - total_loss: 34068.4508

In [ ]:
model.fit(dataset.repeat().shuffle(300_000).batch(4096), steps_per_epoch=50, epochs=30, verbose=1)

In [ ]:
# save the model weights
model._query_model.save_weights(weights_dir.format('query'))
model._candidate_model.save_weights(weights_dir.format('candidate'))

In [ ]:
# create the index model to lookup the best candidate match for a query
index = tfrs.layers.factorized_top_k.BruteForce(model._query_model)
index.index_from_dataset(
    tf.data.Dataset.zip((
      dataset.map(lambda x: x['user']).batch(100),
      dataset.batch(100).map(lambda x: model._candidate_model(x['user']))
    ))
)
for features in dataset.shuffle(2000).batch(1).take(1):
    print('songs', features['songs'])
    scores, users = index(features['songs'])
    print('recommended users', users)

In [ ]:
# save the index model
index.save(index_model_dir)